// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBts-bWPHUK3hTXtiAdd8KkbNuq3EYqGfI',
    appId: '1:874921514581:android:f13ebf2dc3293b736d66dc',
    messagingSenderId: '874921514581',
    projectId: 'trash-add22',
    databaseURL: 'https://trash-add22-default-rtdb.firebaseio.com',
    storageBucket: 'trash-add22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDPlHIlNACtFCL7SQftcnWhMYOa6jkAaA',
    appId: '1:874921514581:ios:b8fc20abbeaf7e4e6d66dc',
    messagingSenderId: '874921514581',
    projectId: 'trash-add22',
    databaseURL: 'https://trash-add22-default-rtdb.firebaseio.com',
    storageBucket: 'trash-add22.appspot.com',
    androidClientId: '874921514581-80k0ob7vlk8coc3m8tufar0rk56b9sci.apps.googleusercontent.com',
    iosClientId: '874921514581-a7rmbhvnhfohk9jc8lb2mo1brgn9i912.apps.googleusercontent.com',
    iosBundleId: 'com.adinath.shiksha',
  );
}
